### ISSUE TITLE
Delete subscription

### ISSUE THREAD

**Issue by abnerjacobsen** [Tiledesk/tiledesk-server#21]
Hi,

I'm integrating my company robot with Tiledesk and in the process created a test webhook subscription. Now I want to change the original subscription to another URL. How I can delete the original subscription using an API call ?

**Comment by andrealeo83** [comment]
you can use this api to delete a subscription https://developer.tiledesk.com/apis/webhooks/subscriptions#delete-a-subscription-by-id

**Comment by abnerjacobsen** [comment]
Thanks, it's worked.
