### ISSUE TITLE
Systema messages through API

### ISSUE THREAD

**Issue by abnerjacobsen** [Tiledesk/tiledesk-server#25]
I integrated a system of my company that is an AI bot for confirming medical appointments. In some situations my Bot transfers the conversation to a human being using Tiledesk and becomes a proxy between Tiledesk and the communication channel that the customer is using, like whatsapp, SMS, etc.

From the moment the conversation is established between Tiledesk and the customer, my bot needs, in some situations, to send alert messages to the agent using Tiledesk. I solved this problem by creating an account for my bot in the Tiledesk project and using the API method:

/{id_project}/requests /support-group- {recipient}/messages

But, I would like a more elegant solution, without the need to create a user for my bot on Tiledesk.

My question is:

There is some possibility of using the API to send messages that appear in the chat of the agent like those he receives from the system ?

System
New member added to group

**Comment by andrealeo83** [comment]
Are you using the cloud or the on-premise version?
You can use /{id_project}/requests /support-group- {recipient}/messages REST endpoint with the JWT token of your external bot. You can find info about external bot here: https://developer.tiledesk.com/apis/tutorials/connect-your-own-chatbot

You can send info message (message system) following this guide: 
https://developer.tiledesk.com/apis/rest-api/messages#advanced-features
In detail you must use attributes.subtype field like below: {"attributes": {"subtype":"info"}}

**Comment by abnerjacobsen** [comment]
@andrealeo83 Worked like a charm. Thanks.

I'm using the cloud version.

And tomorrow one of my clients will start testing the integration between Tiledesk and my company's bot. Initially the integration will only be via Whatsapp, but if all goes well, I intend to expand to other channels: SMS, email, Telegram, etc.

For your information my client's admin account is: marca***@cen******.com.br

I would like to translate Tiledesk into Brazilian Portuguese. What are the server and dashboard files that I have to translate?
